export const FEATURED_CATEGORIES = "FEATURED_CATEGORIES";
export const FEATURED_PRODUCTS = "FEATURED_PRODUCTS";
export const PRODUCT_BY_ID = "PRODUCT_BY_ID";
export const REST = "REST";
export const TRENDING_PRODUCTS = "TRENDING_PRODUCTS";
